"""
Command Library for ResourceChecker Console.
Contains categorized lists of Windows commands.
"""

COMMAND_CATEGORIES = {
    'Network': [
        {'name': 'IP Configuration (All)', 'cmd': 'ipconfig /all', 'desc': 'Displays full configuration of all network adapters.', 'desc_tr': 'Tüm ağ bağdaştırıcılarının tam yapılandırmasını görüntüler.'},
        {'name': 'Ping Google', 'cmd': 'ping google.com', 'desc': 'Tests connectivity to Google servers.', 'desc_tr': 'Google sunucularına bağlantıyı test eder.'},
        {'name': 'Ping Localhost', 'cmd': 'ping 127.0.0.1', 'desc': 'Tests local loopback interface.', 'desc_tr': 'Yerel geri döngü arayüzünü (localhost) test eder.'},
        {'name': 'Trace Route (Google)', 'cmd': 'tracert 8.8.8.8', 'desc': 'Traces path to Google DNS.', 'desc_tr': 'Google DNS sunucusuna giden paket yolunu izler.'},
        {'name': 'Netstat (All Ports)', 'cmd': 'netstat -ano', 'desc': 'Displays active connections and listening ports.', 'desc_tr': 'Aktif bağlantıları ve dinlenen portları görüntüler.'},
        {'name': 'ARP Table', 'cmd': 'arp -a', 'desc': 'Displays the ARP (Address Resolution Protocol) cache.', 'desc_tr': 'ARP (Adres Çözümleme Protokolü) önbelleğini görüntüler.'},
        {'name': 'Display DNS Cache', 'cmd': 'ipconfig /displaydns', 'desc': 'Shows contents of the DNS resolver cache.', 'desc_tr': 'DNS çözümleyici önbelleğinin içeriğini gösterir.'},
        {'name': 'Flush DNS', 'cmd': 'ipconfig /flushdns', 'desc': 'Clears the DNS resolver cache.', 'desc_tr': 'DNS çözümleyici önbelleğini temizler.'},
        {'name': 'Route Table', 'cmd': 'route print', 'desc': 'Displays the IP routing table.', 'desc_tr': 'IP yönlendirme tablosunu görüntüler.'},
        {'name': 'NSLookup (Google)', 'cmd': 'nslookup google.com', 'desc': 'Queries DNS for google.com.', 'desc_tr': 'google.com için DNS sorgusu yapar.'},
        {'name': 'WLAN Drivers', 'cmd': 'netsh wlan show drivers', 'desc': 'Shows properties of the wireless network driver.', 'desc_tr': 'Kablosuz ağ sürücüsünün özelliklerini gösterir.'},
        {'name': 'WLAN Interfaces', 'cmd': 'netsh wlan show interfaces', 'desc': 'Shows details of the wireless network interface.', 'desc_tr': 'Kablosuz ağ arayüzünün detaylarını gösterir.'},
        {'name': 'WLAN Networks', 'cmd': 'netsh wlan show networks', 'desc': 'Lists available visible Wi-Fi networks.', 'desc_tr': 'Görünür kablosuz ağları listeler.'},
        {'name': 'WLAN Profiles', 'cmd': 'netsh wlan show profiles', 'desc': 'Lists saved Wi-Fi profiles.', 'desc_tr': 'Kayıtlı Wi-Fi profillerini listeler.'},
        {'name': 'TCP/IP Reset', 'cmd': 'netsh int ip reset', 'desc': 'Resets TCP/IP stack (Requires Restart).', 'desc_tr': 'TCP/IP yığınını sıfırlar (Yeniden başlatma gerektirir).'},
        {'name': 'Winsock Reset', 'cmd': 'netsh winsock reset', 'desc': 'Resets Winsock Catalog (Requires Restart).', 'desc_tr': 'Winsock kataloğunu sıfırlar (Yeniden başlatma gerektirir).'},
        {'name': 'Test Connection (8.8.8.8)', 'cmd': 'ping 8.8.8.8 -n 5', 'desc': 'Pings Google DNS 5 times.', 'desc_tr': 'Google DNS sunucusuna 5 kez ping atar.'},
        {'name': 'Get MAC Addresses', 'cmd': 'getmac /v', 'desc': 'Detailed MAC address list.', 'desc_tr': 'Detaylı MAC adresi listesi.'},
        {'name': 'Show Open Ports (TCP)', 'cmd': 'netstat -at', 'desc': 'Displays all TCP ports.', 'desc_tr': 'Tüm açık TCP portlarını görüntüler.'},
        {'name': 'Show Open Ports (UDP)', 'cmd': 'netstat -au', 'desc': 'Displays all UDP ports.', 'desc_tr': 'Tüm açık UDP portlarını görüntüler.'},
        {'name': 'Firewall State', 'cmd': 'netsh advfirewall show allprofiles', 'desc': 'Shows status of all firewall profiles.', 'desc_tr': 'Tüm güvenlik duvarı profillerinin durumunu gösterir.'},
    ],
    'System': [
        {'name': 'System Info', 'cmd': 'systeminfo', 'desc': 'Detailed system configuration information.', 'desc_tr': 'Detaylı sistem yapılandırma bilgisi.'},
        {'name': 'CPU Name', 'cmd': 'wmic cpu get name', 'desc': 'Displays the authentic name of the CPU.', 'desc_tr': 'İşlemcinin tam adını görüntüler.'},
        {'name': 'Disk Drive Info', 'cmd': 'wmic DISKDRIVE get model,size,status', 'desc': 'Displays model, size and status of physical disks.', 'desc_tr': 'Fiziksel disklerin model, boyut ve durumunu gösterir.'},
        {'name': 'Driver Query', 'cmd': 'driverquery', 'desc': 'Lists all installed device drivers.', 'desc_tr': 'Yüklü tüm sürücüleri listeler.'},
        {'name': 'Task List', 'cmd': 'tasklist', 'desc': 'Displays all running processes.', 'desc_tr': 'Çalışan tüm işlemleri görüntüler.'},
        {'name': 'Environment Vars', 'cmd': 'set', 'desc': 'Displays all environment variables.', 'desc_tr': 'Tüm ortam değişkenlerini görüntüler.'},
        {'name': 'Current User', 'cmd': 'whoami', 'desc': 'Displays current user name.', 'desc_tr': 'Mevcut kullanıcı adını görüntüler.'},
        {'name': 'Hostname', 'cmd': 'hostname', 'desc': 'Displays computer name.', 'desc_tr': 'Bilgisayar adını görüntüler.'},
        {'name': 'OS Version', 'cmd': 'ver', 'desc': 'Displays Windows version.', 'desc_tr': 'Windows sürümünü görüntüler.'},
        {'name': 'System Uptime', 'cmd': 'net statistics workstation', 'desc': 'Show statistics including uptime.', 'desc_tr': 'Çalışma süresi dahil istatistikleri gösterir.'},
        {'name': 'Check Disk (Read)', 'cmd': 'chkdsk', 'desc': 'Checks file system for errors (Read-only).', 'desc_tr': 'Dosya sistemini hatalara karşı kontrol eder (Salt okunur).'},
        {'name': 'SFC Scan', 'cmd': 'sfc /scannow', 'desc': 'Scans integrity of all protected system files (Admin).', 'desc_tr': 'Korunan sistem dosyalarının bütünlüğünü tarar (Yönetici).'},
        {'name': 'DISM Check Health', 'cmd': 'DISM /Online /Cleanup-Image /CheckHealth', 'desc': 'Checks for corruption (Fast).', 'desc_tr': 'Bozulmaları kontrol eder (Hızlı).'},
        {'name': 'DISM Scan Health', 'cmd': 'DISM /Online /Cleanup-Image /ScanHealth', 'desc': 'Scans for corruption (Slow).', 'desc_tr': 'Bozulmaları tarar (Yavaş).'},
        {'name': 'DISM Restore Health', 'cmd': 'DISM /Online /Cleanup-Image /RestoreHealth', 'desc': 'Repairs corruption (Admin/Slow).', 'desc_tr': 'Bozulmaları onarır (Yönetici/Yavaş).'},
        {'name': 'Running Services', 'cmd': 'net start', 'desc': 'Lists running services.', 'desc_tr': 'Çalışan hizmetleri listeler.'},
        {'name': 'BIOS Serial', 'cmd': 'wmic bios get serialnumber', 'desc': 'Get BIOS serial number.', 'desc_tr': 'BIOS seri numarasını getirir.'},
        {'name': 'Motherboard Info', 'cmd': 'wmic baseboard get product,Manufacturer', 'desc': 'Get Motherboard Model.', 'desc_tr': 'Anakart model ve üreticisini getirir.'},
        {'name': 'Product Key (Partial)', 'cmd': 'wmic path softwarelicensingservice get OA3xOriginalProductKey', 'desc': 'Attempts to retrieve OEM Product Key.', 'desc_tr': 'OEM Ürün Anahtarını getirmeyi dener.'},
        {'name': 'Computer Domain', 'cmd': 'wmic computersystem get domain', 'desc': 'Shows the domain the computer belongs to.', 'desc_tr': 'Bilgisayarın ait olduğu domaini gösterir.'},
    ],
    'Hardware & Performance': [
        {'name': 'Memory Chip Info', 'cmd': 'wmic memorychip get capacity, speed, manufacturer', 'desc': 'Details about installed RAM sticks.', 'desc_tr': 'Takılı RAM belleklerin detayları.'},
        {'name': 'Battery Report', 'cmd': 'powercfg /batteryreport', 'desc': 'Generates battery health report (HTML).', 'desc_tr': 'Pil sağlığı raporu oluşturur (HTML).'},
        {'name': 'Energy Report', 'cmd': 'powercfg /energy', 'desc': 'Generates energy efficiency report (Admin).', 'desc_tr': 'Enerji verimliliği raporu oluşturur (Yönetici).'},
        {'name': 'Hibernate On', 'cmd': 'powercfg /hibernate on', 'desc': 'Enables hibernation.', 'desc_tr': 'Hazırda bekletmeyi etkinleştirir.'},
        {'name': 'Hibernate Off', 'cmd': 'powercfg /hibernate off', 'desc': 'Disables hibernation (Saves disk space).', 'desc_tr': 'Hazırda bekletmeyi devre dışı bırakır (Disk alanı kazandırır).'},
        {'name': 'GPU Info', 'cmd': 'wmic path Win32_VideoController get name, driverversion', 'desc': 'Graphics card details.', 'desc_tr': 'Ekran kartı detayları.'},
        {'name': 'Sound Device', 'cmd': 'wmic sounddev get name, status', 'desc': 'Audio device details.', 'desc_tr': 'Ses aygıtı detayları.'},
        {'name': 'Temperature (Probe)', 'cmd': 'wmic /namespace:\\\\root\\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature', 'desc': 'Raw thermal zone temp (x10 Kelvin).', 'desc_tr': 'Ham termal bölge sıcaklığı (Kelvin x10).'},
        {'name': 'CPU Load', 'cmd': 'wmic cpu get loadpercentage', 'desc': 'Current CPU utilization.', 'desc_tr': 'Mevcut CPU kullanım yüzdesi.'},
        {'name': 'Available Memory', 'cmd': 'systeminfo | find "Available Physical Memory"', 'desc': 'Free RAM amount.', 'desc_tr': 'Boş RAM miktarı.'},
        {'name': 'Disk Free Space', 'cmd': 'wmic logicaldisk get caption, freespace, size', 'desc': 'Free space on all drives.', 'desc_tr': 'Tüm sürücülerdeki boş alan.'},
        {'name': 'USB Devices', 'cmd': 'wmic path Win32_USBControllerDevice get Dependent', 'desc': 'List USB controller devices.', 'desc_tr': 'USB kontrolcü aygıtlarını listeler.'},
        {'name': 'Printer List', 'cmd': 'wmic printer get name, default', 'desc': 'List installed printers.', 'desc_tr': 'Yüklü yazıcıları listeler.'},
        {'name': 'Monitor Config', 'cmd': 'wmic desktopmonitor get screenheight, screenwidth', 'desc': 'Screen resolution info.', 'desc_tr': 'Ekran çözünürlük bilgisi.'},
        {'name': 'Boot config', 'cmd': 'bcdedit', 'desc': 'Boot Configuration Data (Admin).', 'desc_tr': 'Önyükleme Yapılandırma Verileri (Yönetici).'},
    ],
    'Security & Permissions': [
        {'name': 'User Accounts', 'cmd': 'net user', 'desc': 'List user accounts.', 'desc_tr': 'Kullanıcı hesaplarını listeler.'},
        {'name': 'Admin Group', 'cmd': 'net localgroup administrators', 'desc': 'List members of Admin group.', 'desc_tr': 'Yöneticiler grubunun üyelerini listeler.'},
        {'name': 'Group Policy Update', 'cmd': 'gpupdate /force', 'desc': 'Force update of Group Policies.', 'desc_tr': 'Grup İlkelerini zorla günceller.'},
        {'name': 'Wipe Free Space (C:)', 'cmd': 'cipher /w:C', 'desc': 'Overwrites deleted data on C drive (Slow).', 'desc_tr': 'C sürücüsündeki silinmiş verilerin üzerine yazar (Yavaş).'},
        {'name': 'User Privileges', 'cmd': 'whoami /priv', 'desc': 'Display current user privileges.', 'desc_tr': 'Mevcut kullanıcının yetkilerini görüntüler.'},
        {'name': 'User Groups', 'cmd': 'whoami /groups', 'desc': 'Display groups current user belongs to.', 'desc_tr': 'Kullanıcının üye olduğu grupları görüntüler.'},
        {'name': 'Account Lockout Policy', 'cmd': 'net accounts', 'desc': 'Password and lockout policy settings.', 'desc_tr': 'Şifre ve hesap kilitleme politikası ayarları.'},
        {'name': 'Firewall Status', 'cmd': 'netsh advfirewall show currentprofile state', 'desc': 'Check if Firewall is ON/OFF.', 'desc_tr': 'Güvenlik duvarının AÇIK/KAPALI durumunu kontrol eder.'},
        {'name': 'Firewall Rules', 'cmd': 'netsh advfirewall firewall show rule name=all', 'desc': 'List all firewall rules (Long output).', 'desc_tr': 'Tüm güvenlik duvarı kurallarını listeler (Uzun çıktı).'},
        {'name': 'Check Admin', 'cmd': 'net session', 'desc': 'Returns 0 if Admin, Access Denied if not.', 'desc_tr': 'Yönetici ise 0, değilse Erişim Engellendi döner.'},
    ],
    'Disk & File': [
        {'name': 'List Directory', 'cmd': 'dir', 'desc': 'List files in current directory.', 'desc_tr': 'Mevcut dizindeki dosyaları listeler.'},
        {'name': 'Tree View', 'cmd': 'tree', 'desc': 'Graphically display folder structure.', 'desc_tr': 'Klasör yapısını grafiksel olarak görüntüler.'},
        {'name': 'Check Dirty Bit', 'cmd': 'fsutil dirty query C:', 'desc': 'Check if C volume is marked as dirty.', 'desc_tr': 'C biriminin kirli (hatalı) işaretlenip işaretlenmediğini kontrol eder.'},
        {'name': 'Disk Partitions', 'cmd': 'wmic partition get name, size, type', 'desc': 'List disk partitions.', 'desc_tr': 'Disk bölümlerini listeler.'},
        {'name': 'Volume Info', 'cmd': 'vol', 'desc': 'Display disk volume label and serial.', 'desc_tr': 'Disk birim etiketini ve seri numarasını görüntüler.'},
        {'name': 'File Associations', 'cmd': 'assoc', 'desc': 'List file extension associations.', 'desc_tr': 'Dosya uzantısı ilişkilendirmelerini listeler.'},
        {'name': 'Open Files', 'cmd': 'openfiles', 'desc': 'List open files (Admin & Flag enabled).', 'desc_tr': 'Açık dosyaları listeler (Yönetici ve Flag etkinse).'},
        {'name': 'List Shares', 'cmd': 'net share', 'desc': 'List network shares.', 'desc_tr': 'Ağ paylaşımlarını listeler.'},
        {'name': 'Shadow Copies', 'cmd': 'vssadmin list shadows', 'desc': 'List Volume Shadow Copies.', 'desc_tr': 'Birim Gölge Kopyalarını listeler.'},
        {'name': 'Disk Quotas', 'cmd': 'fsutil quota query C:', 'desc': 'Query disk quotas.', 'desc_tr': 'Disk kotalarını sorgular.'},
    ],
    'Developer Tools': [
        {'name': 'Dotnet Info', 'cmd': 'dotnet --info', 'desc': '.NET Core SDK/Runtime info.', 'desc_tr': '.NET Core SDK/Runtime bilgisi.'},
        {'name': 'Java Version', 'cmd': 'java -version', 'desc': 'Java Runtime version.', 'desc_tr': 'Java Runtime sürümü.'},
        {'name': 'Maven Version', 'cmd': 'mvn -version', 'desc': 'Maven build tool version.', 'desc_tr': 'Maven yapı aracı sürümü.'},
        {'name': 'ADB Devices', 'cmd': 'adb devices', 'desc': 'Android Debug Bridge connected devices.', 'desc_tr': 'ADB ile bağlı cihazları listeler.'},
        {'name': 'Git Version', 'cmd': 'git --version', 'desc': 'Git version.', 'desc_tr': 'Git sürümü.'},
        {'name': 'Node Version', 'cmd': 'node -v', 'desc': 'Node.js version.', 'desc_tr': 'Node.js sürümü.'},
        {'name': 'NPM Version', 'cmd': 'npm -v', 'desc': 'Node Package Manager version.', 'desc_tr': 'NPM sürümü.'},
        {'name': 'Python Version', 'cmd': 'python --version', 'desc': 'Python version.', 'desc_tr': 'Python sürümü.'},
        {'name': 'PIP Version', 'cmd': 'pip --version', 'desc': 'Python Package Installer version.', 'desc_tr': 'PIP sürümü.'},
        {'name': 'Docker Version', 'cmd': 'docker --version', 'desc': 'Docker container engine version.', 'desc_tr': 'Docker sürümü.'},
        {'name': 'ADB Version', 'cmd': 'adb version', 'desc': 'ADB tool version.', 'desc_tr': 'ADB araç sürümü.'},
        {'name': 'Gradle Version', 'cmd': 'gradle -v', 'desc': 'Gradle build tool version.', 'desc_tr': 'Gradle yapı aracı sürümü.'},
        {'name': 'Go Version', 'cmd': 'go version', 'desc': 'Go language version.', 'desc_tr': 'Go dili sürümü.'},
        {'name': 'Rust Version', 'cmd': 'rustc --version', 'desc': 'Rust compiler version.', 'desc_tr': 'Rust derleyici sürümü.'},
        {'name': 'GCC Version', 'cmd': 'gcc --version', 'desc': 'GCC compiler version.', 'desc_tr': 'GCC derleyici sürümü.'},
    ]
}
